### ISSUE TITLE
Request for Publication on Chrome Official Store

### ISSUE THREAD

**Issue by xhiroga** [bilzard/ar5iv-button#1]
Thank you for the wonderful features. I would love to use them.
Would it be possible to publish them on the Chrome Web Store and provide the link here?
I found some pre-built versions through a search ([results](https://ar5iv-button.softonic.jp/chrome/extension)), but since they are not on the official store, their safety is uncertain.

**Comment by bilzard** [comment]
@xhiroga I'm sorry, but since I am not using chrome browser anymore, I am no plan for re-publishing this extension.

However, ArXiv is currently providing beta version of HTML viewing experiences.
Maybe its better than using third-party extensions.

https://blog.arxiv.org/2023/12/21/accessibility-update-arxiv-now-offers-papers-in-html-format/
